version: "3.7"
services:
  server:
    container_name: go-kozel-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    hostname: go-kozel-server
    restart: always
    volumes:
      - ./pb_data:/bin/pb_data
      - ./pb_public:/bin/pb_public 
      - ./pb_migrations:/bin/pb_migrations
  web:
    container_name: go-kozel-web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:80
    hostname: go-kozel-web
    restart: unless-stopped
    depends_on:
      - server
    environment:
      - VITE_API_URL=${VITE_API_URL}