version: "3.7"
services:
  server:
    container_name: server-kozel
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    hostname: server-kozel
    restart: unless-stopped