version: "3.7"
services:
  web:
    container_name: go-kozel-web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:80
    hostname: go-kozel-web
    restart: unless-stopped
